// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bydysaxekylaqugxogle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZHlzYXhla3lsYXF1Z3hvZ2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTg3MzYsImV4cCI6MjA3Mjk5NDczNn0.brt7oYaqqk3cQ2D2leTGAB9pL669YTi0nd0h28r622g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});